<?php
	
/*
	Question2Answer by Gideon Greenspan and contributors

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 vastaus',
		'1_comment' => '1 kommentti',
		'1_day' => '1 päivä',
		'1_disliked' => '1 inhousta',
		'1_flag' => '1 liputus',
		'1_hour' => '1 tunti',
		'1_liked' => '1 peukku',
		'1_minute' => '1 minuutti',
		'1_month' => '1 kuukausi',
		'1_point' => '1 piste',
		'1_question' => '1 kysymys',
		'1_second' => '1 sekunti',
		'1_tag' => '1 tagi',
		'1_user' => '1 käyttäjä',
		'1_view' => '1 lukukerta',
		'1_vote' => '1 ääni',
		'1_week' => '1 viikko',
		'1_year' => '1 vuosi',
		'add_category_x_favorites' => 'Lisää kategoria: ^ suosikkeihini',
		'add_favorites' => 'Lisää suosikkeihini',
		'add_tag_x_favorites' => 'Lisää tagi: ^ suosikkeihini',
		'all_categories' => 'Kaikki kategoriat',
		'anonymous' => 'Anonyymi',
		'answer_edited' => 'vastausta on muokattu',
		'answer_reshown' => 'Vastaus näytetään uudelleen',
		'answer_selected' => 'Vastaus valittu',
		'answered_qs_in_x' => '^ liittyvät kysymykset joissa eniten vastauksia',
		'answered_qs_title' => 'Kysymykset joissa eniten vastauksia',
		'answered' => 'vastattu',
		'asked_related_q' => 'liittyvät kysymykset',
		'asked' => 'kysytty',
		'by_x' => 'käyttäjän ^ toimesta',
		'cancel_button' => 'Keskeytä',
		'closed' => 'suljettu',
		'comment_edited' => 'kommenttia on muokattu',
		'comment_moved' => 'kommentti siirretty',
		'comment_reshown' => 'kommentti näytetään uudelleen',
		'commented' => 'kommentoija',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'tammikuuta',
		'date_month_2' => 'helmikuuta',
		'date_month_3' => 'maaliskuuta',
		'date_month_4' => 'huhtikuuta',
		'date_month_5' => 'toukokuuta',
		'date_month_6' => 'kesäkuuta',
		'date_month_7' => 'heinäkuuta',
		'date_month_8' => 'elokuuta',
		'date_month_9' => 'syyskuuta',
		'date_month_10' => 'lokakuuta',
		'date_month_11' => 'marraskuuta',
		'date_month_12' => 'joulukuuta',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'muokattu',
		'field_required' => 'vaadittu tieto, täytä jollain',
		'general_error' => 'Palvelinvirhe havaittu - yritä uudelleen.',
		'hidden' => 'piilotettu',
		'highest_users' => 'Top käyttäjälista, käyttäjät joilla eniten pisteitä',
		'hot_qs_in_x' => 'Suositut kysymykset kategoriassa ^',
		'hot_qs_title' => 'Suositut kysymykset',
		'image_not_read' => 'Kuvaa ei pystytty lukemaan. Hyväksytyt tiedostotyypit ovat: ^',
		'image_too_big_x_pc' => 'Kuva on liian iso. Muuta kooksi ^%, jonka jälkeen yritä uudelleen.',
		'in_category_x' => 'kategoriassa ^, ',
		'ip_address_x' => 'IP-osoite ^',
		'logged_in_x' => 'Hei ^',
		'max_length_x' => 'Suurin sallittu pituus on ^ merkkiä',
		'me' => 'minä',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Lisätietoja vaaditaan (vähimmäispituus ^ merkkiä)',
		'max_upload_size_x' => 'Tiedoston suurin sallittu koko on ^',
		'moved' => 'siirretty',
		'nav_activity' => 'Kaikki aktiivisuus',
		'nav_admin' => 'Hallinnointi',
		'nav_ask' => 'Kysy kysymys',
		'nav_categories' => 'Kategoriat',
		'nav_feedback' => 'Lähetä palautetta',
		'nav_home' => 'Koti',
		'nav_hot' => 'Polttavat!',
		'nav_login' => 'Kirjaudu sisään',
		'nav_logout' => 'Kirjaudu ulos',
		'nav_most_answers' => 'Eniten vastauksia',
		'nav_most_recent' => 'Uusimmat',
		'nav_most_views' => 'Eniten lukukertoja',
		'nav_most_votes' => 'Eniten peukutuksia',
		'nav_no_answer' => 'Vastaamatta',
		'nav_no_selected_answer' => 'Ei valittua vastausta',
		'nav_no_upvoted_answer' => 'Ei peukutettua vastausta',
		'nav_qa' => 'Kysymyksiä ja vastauksia',
		'nav_qs' => 'Kysymyksiä',
		'nav_register' => 'Rekisteröidy',
		'nav_tags' => 'Tagia',
		'nav_unanswered' => 'Vastaamatta',
		'nav_updates' => 'Päivitykseni',
		'nav_users' => 'Käyttäjät',
		'no_active_users' => 'Ei aktiivisia käyttäjiä',
		'no_answers_found' => 'Ei löytynyt vastauksia',
		'no_answers_in_x' => 'Ei vastauksia ^:ssa',
		'no_categories_found' => 'Ei kategorioita',
		'no_category' => 'Kategoria puuttuu',
		'no_comments_found' => 'Ei löytynyt kommentteja',
		'no_comments_in_x' => 'Ei kommentteja ^:ssa',
		'no_questions_found' => 'Ei löytynyt kysymyksiä',
		'no_questions_in_x' => 'Ei kysymyksiä kategoriassa ^',
		'no_related_qs_title' => 'Tähän liittyviä kysymyksiä ei löytynyt',
		'no_results_for_x' => 'Ei tuloksia haulle: ^',
		'no_tags_found' => 'Tageja ei löytynyt',
		'no_una_questions_found' => 'Jihuu! Ei löytynyt vastaamattomia kysymyksiä',
		'no_una_questions_in_x' => 'Ei vastaamattomia kysymyksiä ^:ssa',
		'no_unselected_qs_found' => 'Ei kysymyksiä, joissa ei olisi valittua vastausta',
		'no_unupvoteda_qs_found' => 'Ei kysymyksiä, joissa ei olisi peukutettua vastausta',
		'page_label' => 'Sivu:',
		'page_next' => 'seuraava',
		'page_not_found' => 'Sivua ei löytynyt',
		'page_prev' => 'edellinen',
		'popular_tags' => 'Suositut tagit',
		'questions_tagged_x' => 'Viimeisimmät kysymykset tagissa ^',
		'recategorized' => 'uudelleenkategorisoitu',
		'recent_activity_in_x' => 'Viimeisin toiminnallisuus ^:ssa',
		'recent_activity_title' => 'Viimeisin toiminnallisuus',
		'recent_as_in_x' => 'Viimeksi vastatut kysymykset kategoriassa ^',
		'recent_as_title' => 'Viimeksi vastatut kysymykset',
		'recent_cs_in_x' => 'Viimeisimmät kommentoidut kysymykset kategoriassa ^',
		'recent_cs_title' => 'Viimeisimmät kommentoidut kysymykset',
		'recent_qs_as_in_x' => 'Viimeisimmät kysymykset ja vastaukset kategoriassa ^',
		'recent_qs_as_title' => 'Viimeisimmät kysymykset ja vastaukset',
		'recent_qs_in_x' => 'Viimeisimmät kysymykset kategoriassa ^',
		'recent_qs_title' => 'Viimeisimmät kysymykset',
		'related_qs_title' => 'Liittyvät kysymykset',
		'remove_favorites' => 'Poista suosikeistani',
		'remove_x_favorites' => 'Poista ^ suosikeistani',
		'reopened' => 'Avattu uudelleen',
		'reshown' => 'Näytetään uudelleen',
		'results_for_x' => 'Etsinnän tulokset hakutermille: ^',
		'retagged' => 'Tagit päivitetty',
		'save_button' => 'Tallenna muutokset',
		'search_button' => 'Etsi',
		'search_explanation' => 'Kirjoita hakutermit ja yritä uudelleen.',
		'search_title' => 'Etsi kysymyksiä',
		'selected' => 'valittu',
		'send_button' => 'Lähetä',
		'suggest_ask' => 'Aloita ^1esittämällä kysymys tai idea^2.',
		'suggest_category_qs' => 'Etsitkö jotain muuta? Lue muut ^1kysymykset tässä kategoriassa^2.',
		'suggest_qs_tags' => 'Etsitkö jotain muuta? Katso myös ^kaikkien kysymysten listaus^2 tai ^3suositut aiheet^4.',
		'suggest_qs' => 'Etsitkö jotain muuta? Katso löytyisikö ^1kaikkien kysymysten listauksesta^2.',
		'unanswered_qs_in_x' => 'Viimeisimmät vastaamattomat kysymykset kategoriassa ^',
		'unanswered_qs_title' => 'Viimeisimmät vastaamattomat kysymykset',
		'unselected_qs_in_x' => 'Kysymykset, joihin ei ole valittu vastausta kategoriassa ^',
		'unselected_qs_title' => 'Viimeisimmät kysymykset ilman valittuja vastauksia',
		'unupvoteda_qs_in_x' => 'Kysymykset ilman kannatusääniä kategoriassa ^',
		'unupvoteda_qs_title' => 'Senaste frågorna som saknar uppröstat svar',
		'upload_limit' => 'Liian monta tiedoston lähetysyritystä - yritä uudelleen tunnin kuluttua',
		'view_q_must_be_approved' => 'Käyttäjätunnuksesi pitää hyväksyä moderaattorien toimesta ennen kuin voit nähdä kysymyssivuja.',
		'view_q_must_confirm' => 'Ole hyvä ja ^5vahvista sähköpostiosoitteesi^6 nähdäksesi kysymykset.',
		'view_q_must_login' => 'Ole hyvä ja ^1kirjaudu sisään^2 tai ^3rekisteröidy^4  nähdäksesi kysymykset.',
		'viewed_qs_in_x' => 'Kysymykset, joita näytetty eniten kategoriassa ^',
		'viewed_qs_title' => 'Kysymykset, joita katsottu eniten',
		'vote_disabled_approve' => 'Käyttäjätunnuksesi pitää hyväksyä moderaattorien toimesta ennen kuin voit äänestää',
		'vote_disabled_down' => 'Ned-röstning är endast tillgänglig för vissa användare',
		'vote_disabled_down_approve' => 'Käyttäjätunnuksesi pitää hyväksyä moderaattorien toimesta ennen kuin voit äänestää alaspäin',
		'vote_disabled_hidden_a' => 'Et voi äänestää piilotettua vastausta',
		'vote_disabled_hidden_q' => 'Et voi äänestää piilotettua kysymystä',
		'vote_disabled_level' => 'Äänestäminen on sallittu vain tietyille käyttäjille',
		'vote_disabled_my_a' => 'Et voi äänestää omaa vastaustasi',
		'vote_disabled_my_q' => 'Et voi äänestää omaa kysymystäsi',
		'vote_disabled_q_page_only' => 'Ole hyvä ja siirry kysymykseen äänestääksesi',
		'vote_down_must_confirm' => '^5Vahvista sähköpostiosoitteesi^6 äänestääksesi alaspäin.',
		'vote_down_popup' => 'Valitse peukuttaaksesi alaspäin',
		'vote_limit' => 'Olet antanut liian monta ääntä lyhyessä ajassa - odota 1 tunti ja yritä uudelleen',
		'vote_must_confirm' => 'Ole hyvä ja ^5vahvista sähköpostiosoitteesi^6 äänestystä varten.',
		'vote_must_login' => '^1Kirjaudu sisään^2 tai ^3rekisteröidy^4 äänestääksesi.',
		'vote_not_allowed' => 'Äänestys on tämän kohdalla suljettu',
		'vote_up_popup' => 'Valitse peukuttaaksesi ylöspäin',
		'voted_down_popup' => 'Peukutit alaspäin - peruuta peukutus valitsemalla uudelleen',
		'voted_qs_in_x' => 'Kysymykset, joilla eniten ääniä kategoriassa ^',
		'voted_qs_title' => 'Kysymykset, joilla eniten ääniä',
		'voted_up_popup' => 'Peukutit ylöspäin - peruuta peukutus valitsemalla uudelleen',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ sitten',
		'x_answers' => '^ vastausta',
		'x_comments' => '^ kommenttia',
		'x_days' => '^ päivää',
		'x_disliked' => '^ inhousta',
		'x_flags' => '^ liputusta',
		'x_hours' => '^ tuntia',
		'x_liked' => '^ peukkua',
		'x_minutes' => '^ minuuttia',
		'x_months' => '^ kuukautta',
		'x_points' => '^ pistettä',
		'x_questions' => '^ kysymystä',
		'x_seconds' => '^ sekuntia',
		'x_tags' => '^ tagia',
		'x_users' => '^ käyttäjää',
		'x_views' => '^ lukukertaa',
		'x_votes' => '^ ääntä',
		'x_weeks' => '^ viikkoa',
		'x_years' => '^ vuotta',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/