<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-admin.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => '',
		'add_category_button' => '',
		'add_field_button' => '',
		'add_link_button' => '',
		'add_link_link' => '',
		'add_new_field' => '',
		'add_new_title' => '',
		'add_page_button' => '',
		'add_title_button' => '',
		'add_widget_button' => '',
		'add_widget_link' => '',
		'admin_title' => '',
		'after_footer' => '',
		'after_main_menu' => '',
		'after_x' => '',
		'after_x_tab' => '',
		'approve_user_popup' => '',
		'approve_users_title' => '',
		'basic_editor' => '',
		'before_main_menu' => '',
		'blobs_directory_error' => '',
		'blobs_move_complete' => '',
		'blobs_move_moved' => '',
		'blobs_stop' => '',
		'blobs_to_db' => '',
		'blobs_to_db_note' => '',
		'blobs_to_disk' => '',
		'blobs_to_disk_note' => '',
		'block_button' => '',
		'block_ips_note' => '',
		'block_user_popup' => '',
		'block_words_note' => '',
		'cancel_mailing_button' => '',
		'categories' => '',
		'categories_introduction' => '',
		'categories_not_shown' => '',
		'categories_title' => '',
		'category_add_sub' => '',
		'category_added' => '',
		'category_already_used' => '',
		'category_default_slug' => '',
		'category_description' => '',
		'category_max_depth_x' => '',
		'category_move_parent' => '',
		'category_name' => '',
		'category_name_first' => '',
		'category_no_add_subs_x' => '',
		'category_no_delete_subs' => '',
		'category_no_sub_error' => '',
		'category_no_sub_to' => '',
		'category_no_subs' => '',
		'category_none_error' => '',
		'category_none_to' => '',
		'category_parent' => '',
		'category_saved' => '',
		'category_slug' => '',
		'category_subs' => '',
		'category_top_level' => '',
		'characters' => '',
		'check_language_suffix' => '',
		'click_name_edit' => '',
		'database_cleanup' => '',
		'delete_category' => '',
		'delete_category_reassign' => '',
		'delete_field' => '',
		'delete_hidden' => '',
		'delete_hidden_complete' => '',
		'delete_hidden_note' => '',
		'delete_link' => '',
		'delete_page' => '',
		'delete_stop' => '',
		'delete_title' => '',
		'delete_widget_position' => '',
		'edit_custom_page' => '',
		'edit_field' => '',
		'edit_link' => '',
		'edit_page' => '',
		'edit_title' => '',
		'emails_per_minute' => '',
		'emails_title' => '',
		'feed_link' => '',
		'feed_link_example' => '',
		'feeds_title' => '',
		'field_link_url' => '',
		'field_multi_line' => '',
		'field_name' => '',
		'field_single_line' => '',
		'field_type' => '',
		'first' => '',
		'flagged_title' => '',
		'form_security_expired' => '',
		'from_anon' => '',
		'from_users' => '',
		'general_title' => '',
		'hidden_answers_deleted' => '',
		'hidden_comments_deleted' => '',
		'hidden_questions_deleted' => '',
		'hidden_title' => '',
		'hotness_factors' => '',
		'ip_address_pages' => '',
		'layout_title' => '',
		'link_name' => '',
		'link_new_window' => '',
		'link_url' => '',
		'lists_title' => '',
		'mailing_complete' => '',
		'mailing_explanation' => '',
		'mailing_progress' => '',
		'mailing_title' => '',
		'mailing_unsubscribe' => '',
		'maintenance_admin_only' => '',
		'maximum_x' => '',
		'moderate_title' => '',
		'module_x_database_init' => '',
		'most_flagged_title' => '',
		'mysql_version' => '',
		'nav_links_explanation' => '',
		'nav_qa_is_home' => '',
		'neat_urls_note' => '',
		'no_approve_found' => '',
		'no_classification' => '',
		'no_flagged_found' => '',
		'no_hidden_found' => '',
		'no_image_gd' => '',
		'no_link' => '',
		'no_multibyte' => '',
		'no_privileges' => '',
		'no_unapproved_found' => '',
		'not_logged_in' => '',
		'opposite_main_menu' => '',
		'options' => '',
		'options_reset' => '',
		'options_saved' => '',
		'page_already_used' => '',
		'page_content_html' => '',
		'page_default_slug' => '',
		'page_heading' => '',
		'page_name' => '',
		'page_slug' => '',
		'pages_explanation' => '',
		'pages_title' => '',
		'pause_mailing_button' => '',
		'per_ip_hour' => '',
		'per_user_hour' => '',
		'permissions_title' => '',
		'permit_to_view' => '',
		'php_version' => '',
		'pixels' => '',
		'plugin_module' => '',
		'plugin_pages_explanation' => '',
		'plugins_title' => '',
		'points' => '',
		'points_defaults_shown' => '',
		'points_required' => '',
		'points_title' => '',
		'position' => '',
		'posting_title' => '',
		'profile_fields' => '',
		'q2a_build_date' => '',
		'q2a_db_size' => '',
		'q2a_db_version' => '',
		'q2a_latest_version' => '',
		'q2a_version' => '',
		'question_lists' => '',
		'question_pages' => '',
		'recalc_categories' => '',
		'recalc_categories_backpaths' => '',
		'recalc_categories_complete' => '',
		'recalc_categories_note' => '',
		'recalc_categories_recounting' => '',
		'recalc_categories_updated' => '',
		'recalc_points' => '',
		'recalc_points_complete' => '',
		'recalc_points_note' => '',
		'recalc_points_recalced' => '',
		'recalc_points_usercount' => '',
		'recalc_posts_count' => '',
		'recalc_stop' => '',
		'recent_approve_title' => '',
		'recent_hidden_title' => '',
		'recount_posts' => '',
		'recount_posts_as_recounted' => '',
		'recount_posts_complete' => '',
		'recount_posts_note' => '',
		'recount_posts_stop' => '',
		'recount_posts_votes_recounted' => '',
		'refill_events' => '',
		'refill_events_complete' => '',
		'refill_events_note' => '',
		'refill_events_refilled' => '',
		'registration_fields' => '',
		'reindex_content' => '',
		'reindex_content_note' => '',
		'reindex_content_stop' => '',
		'reindex_pages_reindexed' => '',
		'reindex_posts_complete' => '',
		'reindex_posts_reindexed' => '',
		'reindex_posts_wordcounted' => '',
		'requires_php_version' => '',
		'requires_q2a_version' => '',
		'reset_options_button' => '',
		'reset_options_confirm' => '',
		'resume_mailing_button' => '',
		'save_options_button' => '',
		'save_recalc_button' => '',
		'save_view_button' => '',
		'send_test_button' => '',
		'show_defaults_button' => '',
		'show_on_register_form' => '',
		'slug_bad_chars' => '',
		'slug_reserved' => '',
		'spam_title' => '',
		'start_mailing_button' => '',
		'stats_title' => '',
		'stop_recalc_warning' => '',
		'tag_pages' => '',
		'tags' => '',
		'tags_and_categories' => '',
		'tags_not_shown' => '',
		'test_sent_to_x' => '',
		'title_already_used' => '',
		'top_level_categories' => '',
		'total_as' => '',
		'total_cs' => '',
		'total_qs' => '',
		'unnamed_plugin' => '',
		'upgrade_db' => '',
		'url_format_note' => '',
		'user_pages' => '',
		'user_title' => '',
		'user_titles' => '',
		'users_active' => '',
		'users_must_have' => '',
		'users_posted' => '',
		'users_registered' => '',
		'users_title' => '',
		'users_voted' => '',
		'version_get_x' => '',
		'version_latest' => '',
		'version_latest_unknown' => '',
		'version_requires_php' => '',
		'version_requires_q2a' => '',
		'viewing_title' => '',
		'widget_all_pages' => '',
		'widget_global_options' => '',
		'widget_name' => '',
		'widget_no_positions' => '',
		'widget_not_available' => '',
		'widget_pages_explanation' => '',
		'widgets_explanation' => '',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
