<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => '',
		'allow_close_questions' => '',
		'allow_login_email_only' => '',
		'allow_multi_answers' => '',
		'allow_no_category' => '',
		'allow_no_sub_category' => '',
		'allow_private_messages' => 'Salli yksityisviestit käyttäjien välillä:',
		'allow_self_answer' => '',
		'allow_user_walls' => '',
		'allow_view_q_bots' => '',
		'approve_user_required' => '',
		'avatar_allow_gravatar' => '',
		'avatar_allow_upload' => '',
		'avatar_default_show' => '',
		'avatar_message_list_size' => '',
		'avatar_profile_size' => '',
		'avatar_q_list_size' => '',
		'avatar_q_page_a_size' => '',
		'avatar_q_page_c_size' => '',
		'avatar_q_page_q_size' => '',
		'avatar_store_size' => '',
		'avatar_users_size' => '',
		'block_bad_words' => '',
		'block_ips_write' => '',
		'captcha_module' => '',
		'captcha_on_anon_post' => '',
		'captcha_on_feedback' => '',
		'captcha_on_register' => '',
		'captcha_on_reset_password' => '',
		'captcha_on_unapproved' => '',
		'captcha_on_unconfirmed' => '',
		'columns_tags' => '',
		'columns_users' => '',
		'comment_on_as' => '',
		'comment_on_qs' => '',
		'confirm_user_emails' => '',
		'confirm_user_required' => '',
		'custom_home_content' => '',
		'custom_home_heading' => '',
		'default_privacy' => '',
		'default_sidebar' => '',
		'default_subject' => '',
		'default_suffix' => '',
		'default_terms' => '',
		'do_ask_check_qs' => '',
		'do_close_on_select' => '',
		'do_complete_tags' => '',
		'do_count_q_views' => '',
		'do_example_tags' => '',
		'editor_for_as' => '',
		'editor_for_cs' => '',
		'editor_for_qs' => '',
		'email_privacy' => '',
		'extra_field_active' => '',
		'extra_field_display' => '',
		'extra_field_display_label' => '',
		'feed_for_activity' => '',
		'feed_for_hot' => '',
		'feed_for_qa' => '',
		'feed_for_questions' => '',
		'feed_for_search' => '',
		'feed_for_tag_qs' => '',
		'feed_for_unanswered' => '',
		'feed_full_text' => '',
		'feed_number_items' => '',
		'feed_per_category' => '',
		'feedback_email' => '',
		'feedback_enabled' => '',
		'flagging_hide_after' => '',
		'flagging_notify_every' => '',
		'flagging_notify_first' => '',
		'flagging_of_posts' => '',
		'follow_on_as' => '',
		'from_email' => '',
		'hot_weight_a_age' => '',
		'hot_weight_answers' => '',
		'hot_weight_q_age' => '',
		'hot_weight_views' => '',
		'hot_weight_votes' => '',
		'links_in_new_window' => '',
		'logo_height' => '',
		'logo_show' => '',
		'logo_url' => '',
		'logo_width' => '',
		'mailing_body' => '',
		'mailing_enabled' => '',
		'mailing_from_email' => '',
		'mailing_from_name' => '',
		'mailing_per_minute' => '',
		'mailing_subject' => '',
		'match_1' => '',
		'match_2' => '',
		'match_3' => '',
		'match_4' => '',
		'match_5' => '',
		'match_ask_check_qs' => '',
		'match_example_tags' => '',
		'match_related_qs' => '',
		'max_len_q_title' => '',
		'max_num_q_tags' => '',
		'max_rate_ip_as' => '',
		'max_rate_ip_cs' => '',
		'max_rate_ip_flags' => '',
		'max_rate_ip_logins' => '',
		'max_rate_ip_messages' => '',
		'max_rate_ip_qs' => '',
		'max_rate_ip_registers' => '',
		'max_rate_ip_uploads' => '',
		'max_rate_ip_votes' => '',
		'max_rate_user_as' => '',
		'max_rate_user_cs' => '',
		'max_rate_user_flags' => '',
		'max_rate_user_messages' => '',
		'max_rate_user_qs' => '',
		'max_rate_user_uploads' => '',
		'max_rate_user_votes' => '',
		'min_len_a_content' => '',
		'min_len_c_content' => '',
		'min_len_q_content' => '',
		'min_len_q_title' => '',
		'min_num_q_tags' => '',
		'moderate_anon_post' => '',
		'moderate_by_points' => '',
		'moderate_edited_again' => '',
		'moderate_notify_admin' => '',
		'moderate_points_limit' => '',
		'moderate_unapproved' => '',
		'moderate_unconfirmed' => '',
		'moderate_update_time' => '',
		'moderate_users' => '',
		'neat_urls' => '',
		'notify_admin_q_post' => '',
		'notify_users_default' => '',
		'option_default' => '',
		'page_size_activity' => '',
		'page_size_ask_check_qs' => '',
		'page_size_ask_tags' => '',
		'page_size_home' => '',
		'page_size_hot_qs' => '',
		'page_size_pms' => '',
		'page_size_q_as' => '',
		'page_size_qs' => '',
		'page_size_related_qs' => '',
		'page_size_search' => '',
		'page_size_tag_qs' => '',
		'page_size_tags' => '',
		'page_size_una_qs' => '',
		'page_size_users' => '',
		'page_size_wall' => '',
		'pages_prev_next' => '',
		'permit_admins' => '',
		'permit_all' => '',
		'permit_approve_users' => '',
		'permit_approved' => '',
		'permit_approved_points' => '',
		'permit_block' => '',
		'permit_confirmed' => '',
		'permit_create_admins' => '',
		'permit_create_eds_mods' => '',
		'permit_create_experts' => '',
		'permit_delete_users' => '',
		'permit_editors' => '',
		'permit_experts' => '',
		'permit_moderators' => '',
		'permit_points' => '',
		'permit_points_confirmed' => '',
		'permit_see_emails' => '',
		'permit_supers' => '',
		'permit_users' => '',
		'place_full_below_content' => '',
		'place_full_below_footer' => '',
		'place_full_below_nav' => '',
		'place_full_top' => '',
		'place_main_below_lists' => '',
		'place_main_below_title' => '',
		'place_main_bottom' => '',
		'place_main_top' => '',
		'place_side_below_categories' => '',
		'place_side_below_sidebar' => '',
		'place_side_last' => '',
		'place_side_top' => '',
		'points_a_selected' => '',
		'points_a_voted_max_gain' => '',
		'points_a_voted_max_loss' => '',
		'points_base' => '',
		'points_multiple' => '',
		'points_per_a_voted_down' => '',
		'points_per_a_voted_up' => '',
		'points_per_q_voted_down' => '',
		'points_per_q_voted_up' => '',
		'points_post_a' => '',
		'points_post_q' => '',
		'points_q_voted_max_gain' => '',
		'points_q_voted_max_loss' => '',
		'points_select_a' => '',
		'points_vote_down_a' => '',
		'points_vote_down_q' => '',
		'points_vote_up_a' => '',
		'points_vote_up_q' => '',
		'q_urls_remove_accents' => '',
		'q_urls_title_length' => '',
		'register_notify_admin' => '',
		'search_module' => '',
		'show_a_form_immediate' => '',
		'show_always' => '',
		'show_c_reply_buttons' => '',
		'show_custom_answer' => '',
		'show_custom_ask' => '',
		'show_custom_comment' => '',
		'show_custom_footer' => '',
		'show_custom_header' => '',
		'show_custom_home' => '',
		'show_custom_in_head' => '',
		'show_custom_register' => '',
		'show_custom_sidebar' => '',
		'show_custom_sidepanel' => '',
		'show_custom_welcome' => '',
		'show_fewer_cs_count' => '',
		'show_fewer_cs_from' => '',
		'show_full_date_days' => '',
		'show_home_description' => '',
		'show_if_no_as' => '',
		'show_message_history' => '',
		'show_never' => '',
		'show_notice_visitor' => '',
		'show_notice_welcome' => '',
		'show_post_update_meta' => '',
		'show_register_terms' => '',
		'show_selected_first' => '',
		'show_url_links' => '',
		'show_user_points' => '',
		'show_user_titles' => '',
		'show_view_count_q_page' => '',
		'show_view_counts' => '',
		'show_when_created' => '',
		'site_language' => '',
		'site_maintenance' => '',
		'site_text_direction' => '',
		'site_theme' => '',
		'site_theme_mobile' => '',
		'site_title' => '',
		'site_url' => '',
		'smtp_active' => '',
		'smtp_address' => '',
		'smtp_authenticate' => '',
		'smtp_password' => '',
		'smtp_port' => '',
		'smtp_secure' => '',
		'smtp_secure_none' => '',
		'smtp_username' => '',
		'sort_answers_by' => '',
		'sort_time' => '',
		'sort_votes' => '',
		'suspend_register_users' => '',
		'tag_separator_comma' => '',
		'tags_or_categories' => '',
		'time_approved' => '',
		'time_written' => '',
		'votes_separated' => '',
		'voting_on_as' => '',
		'voting_on_q_page_only' => '',
		'voting_on_qs' => '',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/