<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Salli käyttäjän, jolla on kirjoituksia, vaihtaa käyttäjätunnusta: ',
		'allow_close_questions' => 'Salli kysymysten sulkemisen manuaalisesti:',
		'allow_login_email_only' => 'Sisäänkirjautuminen vain sähköpostiosoitteelle (ei käyttäjätunnuksella):',
		'allow_multi_answers' => 'Salli useita vastauksia per käyttäjä:',
		'allow_no_category' => 'Salli kysymykset ilman kategoriaa',
		'allow_no_sub_category' => 'Salli kysymykset, joissa kategoria määritelty, muttei pelkästään alikategorioita.',
		'allow_private_messages' => 'Salli yksityisviestit käyttäjien välillä:',
		'allow_self_answer' => 'Salli käyttäjien vastata heidän omiin kysymyksiin:',
		'allow_user_walls' => 'Näkyvätkö seinäkirjoitukset käyttäjien profiileissa:',
		'allow_view_q_bots' => 'Salli hakukoneiden indeksointi kysymyssivuilla:',
		'approve_user_required' => 'Kaikki käyttäjätunnukset pitää hyväksyä:',
		'avatar_allow_gravatar' => 'Salli ^1Gravatar^2 avatar:',
		'avatar_allow_upload' => 'Salli käyttäjien ladata oma avatar:',
		'avatar_default_show' => 'Oletusavatar:',
		'avatar_message_list_size' => 'Avatarin koko viestilistalla:',
		'avatar_profile_size' => 'Avatarin koko käyttäjäprofiilisivulla:',
		'avatar_q_list_size' => 'Avatarin koko kysymyslistalla:',
		'avatar_q_page_a_size' => 'Avatarin koko vastauksissa:',
		'avatar_q_page_c_size' => 'Avatarin koko kommenteissa:',
		'avatar_q_page_q_size' => 'Avatarin koko kysymyksissä:',
		'avatar_store_size' => 'Avatar tiedoston maksimi koko:',
		'avatar_users_size' => 'Avatarin koko aktiivisimpien käyttäjien sivulla:',
		'block_bad_words' => 'Sensuroidut sanat - erottele sanat välilä tai pilkulla:',
		'block_ips_write' => 'Estetyt IP-osoitteet - erottele sanat välilä tai pilkulla:',
		'captcha_module' => 'Käytä captcha moduulia:',
		'captcha_on_anon_post' => 'Käytä captchaa anonyymien kirjoituksiin:',
		'captcha_on_feedback' => 'Käytä captchaa palautelomakkeella:',
		'captcha_on_register' => 'Käytä captchaa käyttäjien rekisteröinnissä:',
		'captcha_on_reset_password' => 'Käytä captchaa salasanan resetointilomakkeella:',
		'captcha_on_unapproved' => 'Käytä captchaa jos käyttäjää ei ole vielä hyväksytty:',
		'captcha_on_unconfirmed' => 'Käytä captchaa jos sähköpostia ei ole varmistettu:',
		'columns_tags' => 'Sarakkeiden määrä avainsana sivulla:',
		'columns_users' => 'Sarakkeiden määrä käyttäjien sivulla:',
		'comment_on_as' => 'Salli vastauksien kommentointi:',
		'comment_on_qs' => 'Salli kysymyksien kommentointi:',
		'confirm_user_emails' => 'Vaadi käyttäjän sähköpostiosoitteen varmistus:',
		'confirm_user_required' => 'Kaikkien uusien käyttäjien on varmistettava sähköpostiosoitteensa:',
		'custom_home_content' => 'Etusivun sisältö - HTML sallittu: ',
		'custom_home_heading' => 'Etusivun otsikko:',
		'default_privacy' => 'Yksityisyys: sähköpostiosoitettasi EI jaeta tai myydä kolmansille osapuolille.',
		'default_sidebar' => 'Tervetuloa ^ sivustolle. Sivustolla voit esittää aiheeseen liittyviä kysymyksiä ja vastata muiden kysymyksiin. ',
		'default_subject' => 'Viesti saapunut ^',
		'default_suffix' => 'Kysymys&Vastaus',
		'default_terms' => 'Hyväksyn ^ sivuston käyttöehdot ja tietosuojakäytäntöjen ehdot.',
		'do_ask_check_qs' => 'Ehdota samanlaisia kysymyksiä kysyttäessä:',
		'do_close_on_select' => 'Sulje kysymykset, joissa valittu paras vastaus:',
		'do_complete_tags' => 'Näytä kirjoittaessa avainsanoja, jotka voivat sopia aiheeseen.',
		'do_count_q_views' => 'Laske kysymysten näyttökerrat:',
		'do_example_tags' => 'Näytä esimerkkiavainsanoja, jotka liittyvät kysymykseen:',
		'editor_for_as' => 'Oletuseditori vastauksille:',
		'editor_for_cs' => 'Oletuseditori kommenteille:',
		'editor_for_qs' => 'Oletuseditori kysymyksille:',
		'email_privacy' => 'Tietosuojaan liittyvä huomautus sähköpostiosoitteeseen liittyen - HTML sallittua:',
		'extra_field_active' => 'Muokattava kenttä lisätiedoille kyselylomakkeelle:',
		'extra_field_display' => 'Näytä lisätietokenttä kysymyssivuilla',
		'extra_field_display_label' => 'Näytä lisätietokenttä kysymyssivuilla, joilla avainsana:',
		'feed_for_activity' => 'Viimeisimmät aktiiviteetit -syöte:',
		'feed_for_hot' => 'Kuumat kysymykset -syöte:',
		'feed_for_qa' => 'Viimeisimmät kysymykset ja vastaukset -syöte:',
		'feed_for_questions' => 'Viimeisimmät kysymykset -syöte:',
		'feed_for_search' => 'Syötteet hakutuloksille:',
		'feed_for_tag_qs' => 'Syöte jokaiselle kysymykselle, jossa avainsana:',
		'feed_for_unanswered' => 'Vastaamattomien kysymysten -syöte:',
		'feed_full_text' => 'Sisällytä koko teksti syötteisiin:',
		'feed_number_items' => 'Maksimipituus syötteelle:',
		'feed_per_category' => 'Kategoriakohtaiset syötteet:',
		'feedback_email' => 'Sähköpostiosoite pääkäyttäjän lähettämille viesteille - ei näytetä käyttäjille:',
		'feedback_enabled' => 'Käyttäjien palautteen antoon oma sivu',
		'flagging_hide_after' => 'Piilota kirjoitus, kun tietty määrä liputuksia:',
		'flagging_notify_every' => 'Lähetä sähköpostia, joka kerta kun liputetaan:',
		'flagging_notify_first' => 'Lähetä sähköpostia, kun kirjoitus liputetaan:',
		'flagging_of_posts' => 'Kaikki kirjoitukset voidaan liputtaa:',
		'follow_on_as' => 'Allow questions to be related to answers:',
		'from_email' => 'Sähköpostiosoite sivustolta lähteville sähköposteille:',
		'hot_weight_a_age' => 'Kysymyksellä on uusi vastaus:',
		'hot_weight_answers' => 'Kysymyksellä on useita vastauksia:',
		'hot_weight_q_age' => 'Kysymys on uusi:',
		'hot_weight_views' => 'Kysymyksellä on useita katseluita:',
		'hot_weight_votes' => 'Kysymyksellä on useita peukutuksia ylöspäin:',
		'links_in_new_window' => 'Avaa linkit uuteen ikkunaan:',
		'logo_height' => 'Logon korkeus:',
		'logo_show' => 'Show a logo image in the page header',
		'logo_url' => 'URL of logo - absolute or relative to Q2A root:',
		'logo_width' => 'Logon leveys:',
		'mailing_body' => 'Viestikentän teksti:',
		'mailing_enabled' => 'Salli massapostitukset kaikille käyttäjille',
		'mailing_from_email' => 'Sähköpostiosoitteesta:',
		'mailing_from_name' => 'Nimeltä:',
		'mailing_per_minute' => 'Suurin sallittu viestimäärä:',
		'mailing_subject' => 'Aihekenttä:',
		'match_1' => 'Kapein',
		'match_2' => 'Kapeampi',
		'match_3' => 'Oletus',
		'match_4' => 'Leveämpi',
		'match_5' => 'Levein',
		'match_ask_check_qs' => 'Samankaltaisten kysymyksien osuvuus:',
		'match_example_tags' => 'Esimerkki avainsanojen osuvuus:',
		'match_related_qs' => 'Aihepiiriltään läheisten kysymyksien osuvuus:',
		'max_len_q_title' => 'Kysymyksen otsikon maksimipituus:',
		'max_num_q_tags' => 'Maksimimäärä avainsanoja:',
		'max_rate_ip_as' => 'Maksimi vastaustahti:',
		'max_rate_ip_cs' => 'Maksimi kommentointahti:',
		'max_rate_ip_flags' => 'Maksimi liputustahti:',
		'max_rate_ip_logins' => 'Maksimi kirjautumistahti:',
		'max_rate_ip_messages' => 'Maksimi yksityisviestien ja seinäkirjoituksien luontitahti:',
		'max_rate_ip_qs' => 'Maksimi kysymystahti:',
		'max_rate_ip_registers' => 'Maksimi käyttäjien rekisteröitymistahti:',
		'max_rate_ip_uploads' => 'Maksimi tiedostojen lähetystahti:',
		'max_rate_ip_votes' => 'Maksimi äänestystahti:',
		'max_rate_user_as' => 'Vastauksien maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_cs' => 'Kommenttien maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_flags' => 'Liputuksien maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_messages' => 'Yksityisviestien maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_qs' => 'Kysymysten maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_uploads' => 'Tiedostojen lähettämisten maksimimäärä per käyttäjä per tunti:',
		'max_rate_user_votes' => 'Äänien maksimimäärä per käyttäjä per tunti:',
		'min_len_a_content' => 'Vastauksen minimipituus:',
		'min_len_c_content' => 'Kommentin minimipituus:',
		'min_len_q_content' => 'Kysymyksen viestikentän sisällön minimipituus:',
		'min_len_q_title' => 'Kysymyksen otsikon minimipituus:',
		'min_num_q_tags' => 'Avainsanojen minimimäärä:',
		'moderate_anon_post' => 'Käytä moderointia anonyymien kirjoituksiin:',
		'moderate_by_points' => 'Käytä moderointia käyttäjiin, joilla on vähän pisteitä:',
		'moderate_edited_again' => 'Uudelleen moderoi kysymykset muokkauksen jälkeen:',
		'moderate_notify_admin' => 'Lähetä viesti, kun posti tarvitsee moderointia:',
		'moderate_points_limit' => 'Käytä moderointia käyttäjiin, joilla on vähemmän pisteitä kuin:',
		'moderate_unapproved' => 'Käytä moderointia jos käyttäjää ei ole vielä hyväksytty:',
		'moderate_unconfirmed' => 'Käytä moderointia jos sähköpostiosoitetta ei ole vahvistettu:',
		'moderate_update_time' => 'Aika, joka näytetään moderoiduissa kirjoituksissa:',
		'moderate_users' => 'Kytke käyttäjien hyväksyntävaatimus:',
		'neat_urls' => 'Linkin rakenne:',
		'notify_admin_q_post' => 'Lähetä sähköpostia tähän osoitteeseen, kun uusi kysymys on luotu',
		'notify_users_default' => 'Kytke sähköposti-ilmoituksen valinta oletuksena päälle:',
		'option_default' => 'Oletus',
		'page_size_activity' => 'Aktiivisuus listasivun pituus:',
		'page_size_ask_check_qs' => 'Samankaltaisten kysymysten maksiminäyttömäärä:',
		'page_size_ask_tags' => 'Avainsanavihjeiden maksiminäyttömäärä:',
		'page_size_home' => 'Kysymys&vastaus listasivun pituus:',
		'page_size_hot_qs' => 'Kuumimmat listasivun pituus:',
		'page_size_pms' => 'Yksityisviestien määrä sivulla:',
		'page_size_q_as' => 'Vastauksien maksimimäärä per sivu:',
		'page_size_qs' => 'Kysymys listasivun pituus:',
		'page_size_related_qs' => 'Aiheeseen liittyvien kysymysten maksimimäärä: ',
		'page_size_search' => 'Hakutulosten määrä sivulla:',
		'page_size_tag_qs' => 'Kysymysten määrä avainsanan sivulla:',
		'page_size_tags' => 'Avainsana listasivun pituus:',
		'page_size_una_qs' => 'Vastaamattomien listasivun pituus:',
		'page_size_users' => 'Käyttäjien listasivun pituus:',
		'page_size_wall' => 'Seinäkirjoituksien maksimimäärä per sivu:',
		'pages_prev_next' => 'Linkit edelliselle/seuraavalle sivulle:',
		'permit_admins' => 'Ylläpitäjät',
		'permit_all' => 'Kaikille',
		'permit_approve_users' => 'Hyväksyy rekisteröityneet käyttäjät:',
		'permit_approved' => 'Vain hyväksytyt käyttäjät',
		'permit_approved_points' => 'Hyväksytyt käyttäjät, joilla tarpeeksi pisteitä',
		'permit_block' => 'Käyttäjän IP-osoitteen estäminen ja eston poistaminen:',
		'permit_confirmed' => 'Rekisteröityneet käyttäjät, joilla sähköposti vahvistettu',
		'permit_create_admins' => 'Oikeus muuttaa ylläpitäjiksi:',
		'permit_create_eds_mods' => 'Oikeus muuttaa toimittajiksi ja moderaattoreiksi:',
		'permit_create_experts' => 'Oikeus muokkaa asiantuntijoita:',
		'permit_delete_users' => 'Poistaa käyttäjiä:',
		'permit_editors' => 'Toimittajat, moderaattorit, ylläpitäjät',
		'permit_experts' => 'Asiantuntijat, toimittajat, moderaattorit, ylläpitäjät',
		'permit_moderators' => 'Moderaattorit, ylläpitäjät',
		'permit_points' => 'Rekisteröityneet käyttäjät, joilla tarpeeksi pisteitä',
		'permit_points_confirmed' => 'Rekisteröitynyt, sähköposti vahvistettu ja tarpeeksi pisteitä',
		'permit_see_emails' => 'Näkee käyttäjien sähköpostiosoitteet:',
		'permit_supers' => 'Pääylläpitäjä',
		'permit_users' => 'Rekisteröityneet käyttäjät',
		'place_full_below_content' => 'Full width - Below content',
		'place_full_below_footer' => 'Full width - Below footer',
		'place_full_below_nav' => 'Full width - Below navigation',
		'place_full_top' => 'Full width - Top of page',
		'place_main_below_lists' => 'Main area - Below lists',
		'place_main_below_title' => 'Main area - Below title',
		'place_main_bottom' => 'Main area - Bottom',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Lisää kaikille käyttäjille:',
		'points_multiple' => 'Kerro kaikki pisteet:',
		'points_per_a_voted_down' => 'Vastauksen alaspäin äänestys:',
		'points_per_a_voted_up' => 'Vastauksen ylöspäin äänestys:',
		'points_per_q_voted_down' => 'Kysymyksen alaspäin äänestys:',
		'points_per_q_voted_up' => 'Kysymyksen ylöspäin äänestys:',
		'points_post_a' => 'Vastauksen kirjoittaminen:',
		'points_post_q' => 'Kysymyksen kirjoittaminen:',
		'points_q_voted_max_gain' => 'Limit from up votes on each question:',
		'points_q_voted_max_loss' => 'Limit from down votes on each question:',
		'points_select_a' => 'Selecting an answer for your question:',
		'points_vote_down_a' => 'Vastauksen alaspäin äänestäminen:',
		'points_vote_down_q' => 'Kysymyksen alaspäin äänestäminen:',
		'points_vote_up_a' => 'Vastauksen ylöspäin äänestäminen:',
		'points_vote_up_q' => 'Kysymyksen ylöspäin äänestäminen:',
		'q_urls_remove_accents' => 'Poista kysymysten osoitteista aksentit:',
		'q_urls_title_length' => 'Kysymyksen otsikon pituus osoitteessa: ',
		'register_notify_admin' => 'Lähetä sähköpostia kun uusi käyttäjä on rekisteröitynyt:',
		'search_module' => 'Käytä haku moduulia:',
		'show_a_form_immediate' => 'Näytä vastauslomake välittömästi:',
		'show_always' => 'Usein',
		'show_c_reply_buttons' => 'Näytä vastaa nappi kommenteissa:',
		'show_custom_answer' => 'Muokattava viesti vastauksen syöttölomakkeella - HTML sallittu:',
		'show_custom_ask' => 'Muokattava viesti kysymyksen syöttölomakkeella - HTML sallittu:',
		'show_custom_comment' => 'Muokattava viesti kommentin syöttölomakkeella - HTML sallittu:',
		'show_custom_footer' => 'Muokattava HTML alapalkki kaikilla sivuilla:',
		'show_custom_header' => 'Muokattava HTML yläpalkki kaikilla sivuilla:',
		'show_custom_home' => 'Muokattua sisältöä etusivulla kysymys- ja vastaustoiminnallisuuden sijaan',
		'show_custom_in_head' => 'Muokattava HTML <head> -osio kaikilla sivuilla: ',
		'show_custom_register' => 'Muokattava viesti käyttäjien rekisteröintilomakkeella - HTML sallittu:',
		'show_custom_sidebar' => 'Muokattava HTML sivupalkki kaikilla sivuilla:',
		'show_custom_sidepanel' => 'Muokattava HTML sivupaneeli kaikilla sivuilla:',
		'show_custom_welcome' => 'Muokattu sähköpostiviesti rekisteröityneelle käyttäjälle:',
		'show_fewer_cs_count' => 'Jos ',
		'show_fewer_cs_from' => 'Piilota kommentit, kun tietty määrä liputuksia:',
		'show_full_date_days' => 'Näytä päivämäärä kokonaisena tämän jälkeen:',
		'show_home_description' => 'Sisällytä <meta> kuvaus etusivulle:',
		'show_if_no_as' => 'Jos ei ole vastauksia',
		'show_message_history' => 'Säilytä ja näytä yksityisviestien historia:',
		'show_never' => 'Ei koskaan',
		'show_notice_visitor' => 'Näytä ilmoitus sivun yläosassa sivuston uudelle vierailijalle - HTML sallittu:',
		'show_notice_welcome' => 'Näytä ilmoitus sivun yläosassa uudelle rekisteröityneelle käyttäjälle - HTML sallittu:',
		'show_post_update_meta' => 'Näytä muokkaukset ja päivityksen kirjoituksen metatiedoissa:',
		'show_register_terms' => 'Käyttöehtojen hyväksyntä valinta käyttäjän rekisteröintilomakkeella - HTML sallittu:',
		'show_selected_first' => 'Siirrä valittu vastaus ylimmäksi:',
		'show_url_links' => 'Tunnista URL:t ja merkitse linkiksi kirjoituksissa: ',
		'show_user_points' => 'Näytä pisteet käyttäjätunnuksen vieressä:',
		'show_user_titles' => 'Näytä otsikot käyttäjätunnuksen vieressä:',
		'show_view_count_q_page' => 'Näytä katselumäärät kysymyssivulla:',
		'show_view_counts' => 'Näytä katselumäärät kysymysten listasivulla:',
		'show_when_created' => 'Näytä kirjoituksen luontihetki:',
		'site_language' => 'Sivuston kieli:',
		'site_maintenance' => 'Määritä sivusto ylläpitotilaan',
		'site_text_direction' => 'Sivuston tekstin suunta:',
		'site_theme' => 'Sivuston teema:',
		'site_theme_mobile' => 'Mobiililaitteiden teema:',
		'site_title' => 'Kysymys- ja vastaussivuston nimi:',
		'site_url' => 'Sivuston osoite:',
		'smtp_active' => 'Lähetä sähköpostit SMTP palvelimen kautta kuin lokaalin sähköpostiohjelman',
		'smtp_address' => 'SMTP palvelimen osoite:',
		'smtp_authenticate' => 'Lähetä SMTP käyttäjätunnus ja salasana',
		'smtp_password' => 'SMTP salasana:',
		'smtp_port' => 'SMTP palvelimen portti:',
		'smtp_secure' => 'SMTP salattu yhteys:',
		'smtp_secure_none' => 'Ei ole',
		'smtp_username' => 'SMTP käyttäjätunnus:',
		'sort_answers_by' => 'Lajittele vastaukset: ',
		'sort_time' => 'Aika',
		'sort_votes' => 'Äänet',
		'suspend_register_users' => 'Sulje väliaikaisesti uusien käyttäjien rekisteröinnit:',
		'tag_separator_comma' => 'Käytä pilkkua ainoana avainsanojen erottelijana:',
		'tags_or_categories' => 'Kysymyksen luokittelu:',
		'time_approved' => 'Ajankohta kun vahvistettu',
		'time_written' => 'Ajankohta kun kirjoitettu',
		'votes_separated' => 'Näytä ylös ja alas äänet erikseen:',
		'voting_on_as' => 'Salli vastauksen äänestäminen:',
		'voting_on_q_page_only' => 'Salli kysymyksen äänestäminen vain kysymyssivulla:',
		'voting_on_qs' => 'Salli kysymyksien äänestäminen:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/