<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-admin.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Aktivoidut vimpaimet:',
		'add_category_button' => 'Lisää kategoria',
		'add_field_button' => 'Lisää kenttä',
		'add_link_button' => 'Lisää linkki',
		'add_link_link' => '- ^1lisää linkki^2',
		'add_new_field' => 'Lisää uusi kenttä',
		'add_new_title' => 'Lisää uusi otsikko',
		'add_page_button' => 'Lisää sivu',
		'add_title_button' => 'Lisää otsikko',
		'add_widget_button' => 'Lisää vimpain',
		'add_widget_link' => ' - ^1lisää vimpain^2',
		'admin_title' => 'Ylläpitäjän hallintakeskus',
		'after_footer' => 'Linkkien jälkeen alatunnisteessa',
		'after_main_menu' => 'Välilehtien jälkeen ylhäällä',
		'after_x' => '"^" jälkeen',
		'after_x_tab' => '"^" välilehden jälkeen',
		'approve_user_popup' => 'Hyväksy käyttäjä',
		'approve_users_title' => 'Hyväksy käyttäjät',
		'basic_editor' => 'Peruseditori',
		'before_main_menu' => 'Ennen välilehtiä ylhäällä',
		'blobs_directory_error' => 'Hakemistoon ^, joka määritelty QA_BLOBS_DIRECTORY kohdassa, webpalvelin ei pysty kirjoittamaan.',
		'blobs_move_complete' => 'Ladattujen kuvien ja dokumenttien migraatio on valmis.',
		'blobs_move_moved' => 'Ladattujen kuvien ja dokumenttien ^1:sta ^2:een migraatio',
		'blobs_stop' => 'Lopeta migraatio',
		'blobs_to_db' => 'Tiedostot tietokantaan',
		'blobs_to_db_note' => '- migraatioi kaikki ladatut kuvat ja dokumentit levyltä tietokantaan',
		'blobs_to_disk' => 'Tiedostot levylle',
		'blobs_to_disk_note' => '- migraatioi kaikki ladatut kuvat ja dokumentit tietokannasta levylle tiedostoiksi',
		'block_button' => 'estä',
		'block_ips_note' => 'Käytä viivaa IP-väleihin tai * merkkiä. Esimerkiksi: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_user_popup' => 'Estä käyttäjä',
		'block_words_note' => 'Käytä * merkkiä kirjainten tilalla. Esimerkit: doh (löytää vain sanan doh) , doh* (löytää sanat doh tai dohno) , do*h (löytää sanat doh, dooh, dough).',
		'cancel_mailing_button' => 'Peruuta sähköpostin lähetys',
		'categories' => 'Kategoriat',
		'categories_introduction' => 'Aloittaakseni kategorioiden määrittelyn, paina \'Lisää kategoria\' nappia.',
		'categories_not_shown' => 'Osa kysymyksistä voi olla kategorioissa, joita ei näytetä.',
		'categories_title' => 'Kategoriat',
		'category_add_sub' => 'lisää alikategoria',
		'category_added' => 'Kategoria lisätty',
		'category_already_used' => 'Tämä kategoria on jo käytetty',
		'category_default_slug' => 'kategoria-^',
		'category_description' => 'Valinnainen kategorian kuvaus:',
		'category_max_depth_x' => 'Osa valinnoista voi olla piilotettu estääkseen kategorioiden liiallisen syvyyden kuin ^ tasoa.',
		'category_move_parent' => 'siirrä toisen ylemmän kategorian alle',
		'category_name' => 'Kategorian nimi:',
		'category_name_first' => 'Ensimmäisen kategorian nimi:',
		'category_no_add_subs_x' => 'Tämä kategorialla ei voi olla alikategorioita, koska se on jo ^ tason alapuolella.',
		'category_no_delete_subs' => 'Tätä kategoriaa ei voida poistaa, koska sillä on alikategoria.',
		'category_no_sub_error' => '^q kysymyksillä tässä kategoriassa ei ole alikategorioita - ^1määritä alikategoria^2',
		'category_no_sub_to' => 'Siirrä kysymykset kategoriasta ^ , joilla ei ole alikategorioita:',
		'category_no_subs' => 'Ei ole',
		'category_none_error' => '^q kysymyksillä ei ole kategorioita - ^1määritä kategoria^2',
		'category_none_to' => 'Siirrä kysymys, joka on ilman kategoriaa:',
		'category_parent' => 'Ylemmän tason kategoria:',
		'category_saved' => 'Kategoria tallennettu',
		'category_slug' => 'Kategorian etuliite - URL osa:',
		'category_subs' => 'Alikategoriat:',
		'category_top_level' => 'Ei pääkategorioita (ylätaso)',
		'characters' => 'merkistö',
		'check_language_suffix' => ' - ^1tarkista kielitiedostot^2',
		'click_name_edit' => 'Mukautetut sivut tai linkit:',
		'database_cleanup' => 'Tietokannan puhdistus operaatiot',
		'delete_category' => 'Poista tämä kategoria',
		'delete_category_reassign' => 'Poista tämä kategoria ja siirrä kysymykset kategoriaan:',
		'delete_field' => 'Poista tämä kenttä',
		'delete_hidden' => 'Poista piilotetut kirjoitukset',
		'delete_hidden_complete' => 'Kaikki piilotetut kirjoitukset ilman riippuvuuksia on poistettu',
		'delete_hidden_note' => '- kaikki piilotetut kysymykset, vastaukset ja kommentit ilman riippuvuuksia',
		'delete_link' => 'Poista tämä linkki',
		'delete_page' => 'Poista tämä sivu',
		'delete_stop' => 'Keskeytä poistaminen',
		'delete_title' => 'Poista tämä otsikko',
		'delete_widget_position' => 'Poista tämä vimpain tästä kohtaa',
		'edit_custom_page' => 'Muokkaa muokattavaa sivua',
		'edit_field' => ' - ^1muokkaa kenttää^2',
		'edit_link' => ' - ^1muokkaa linkkiä^2',
		'edit_page' => ' - ^1muokkaa sivua^2',
		'edit_title' => ' - ^1muokkaa otsikkoa^2',
		'emails_per_minute' => 'sähköpostiviestejä per minuutti',
		'emails_title' => 'Sähköposteja',
		'feed_link' => 'Syöte',
		'feed_link_example' => 'Esimerkkisyöte',
		'feeds_title' => 'RSS syötteet:',
		'field_link_url' => 'Linkatut URL',
		'field_multi_line' => 'Useita rivejä tekstiä',
		'field_name' => 'Kentän nimi:',
		'field_single_line' => 'Yksittäinen rivi tekstiä',
		'field_type' => 'Sisällön tyyppi:',
		'first' => 'Ensimmäinen',
		'flagged_title' => 'Liputettu',
		'form_security_expired' => 'Lomakkeen turvakoodi vanhentui - yritä uudelleen',
		'from_anon' => 'Anonyymiltä:',
		'from_users' => 'Käyttäjältä:',
		'general_title' => 'Yleinen',
		'hidden_answers_deleted' => 'Poistettu ^1sta ^2een piilotetut vastaukset, joilla ei ole riippuvuuksia...',
		'hidden_comments_deleted' => 'Poistettu ^1sta ^2een piilotetut kommentit...',
		'hidden_questions_deleted' => 'Poistettu ^1sta ^2een piilotetut kysymykset, joilla ei ole riippuvuuksia...',
		'hidden_title' => 'Piilotettu',
		'hotness_factors' => 'Suhteellinen tärkeys kysymyksen kuumuudelle:',
		'ip_address_pages' => 'IP osoitteiden sivut',
		'layout_title' => 'Ulkoasu',
		'link_name' => 'Linkin teksti:',
		'link_new_window' => 'Avaa linkit uuteen ikkunaan',
		'link_url' => 'Linkin URL - täydellinen tai suhteelinen Q2A sivuston juuresta:',
		'lists_title' => 'Listat',
		'mailing_complete' => 'Sähköpostiviestien lähetys valmis',
		'mailing_explanation' => 'Käyttäjä voi peruuttaa tilauksen käyttäjätilisivulla.',
		'mailing_progress' => 'Sähköpostiviestien lähetys on valmis ^1 ja ^2 käyttäjille...',
		'mailing_title' => 'Sähköpostiviestien lähetys',
		'mailing_unsubscribe' => 'Tilauksen peruutuslinkki lisätään kaikkien viestien alaosaan.',
		'maintenance_admin_only' => 'Sivustosi on ^1ylläpitotilassa^2 ja se on saavuttamattomissa tavallisilta käyttäjiltä.',
		'maximum_x' => ' (maksimi ^)',
		'moderate_title' => 'Moderoida',
		'module_x_database_init' => 'Moduulit ^1 ^2 vaativat muutamia ^3tietokannan valmisteluja^4.',
		'most_flagged_title' => 'Liputettu sisältö',
		'mysql_version' => 'MySQL versio:',
		'nav_links_explanation' => 'Näytä navigointilinkit:',
		'nav_qa_is_home' => 'Kysymys&Vastaus (linkki etusivulle)',
		'neat_urls_note' => ' (vaatii ^1htaccess^2 tiedoston)',
		'no_approve_found' => 'Hyväksyntää odottavaa sisältöä ei ole.',
		'no_classification' => 'Ei ole',
		'no_flagged_found' => 'Liputettua sisältöä ei löytynyt',
		'no_hidden_found' => 'Piilotettua sisältöä ei löytynyt',
		'no_image_gd' => 'Asennettu PHP versio on käännetty ilman GD kuvien käsittelyominaisuutta, joten käyttäjät eivät voi lisätä omia avatareja suoraan.',
		'no_link' => 'Ei linkkiä',
		'no_multibyte' => 'Asennettu PHP versio on käännetty ilman "multibyte string" tukea. Haku on vähemmän tehokas ei roomalaisten merkistöjen suhteen.',
		'no_privileges' => 'Vain ylläpitäjillä on oikeudet tälle sivulle.',
		'no_unapproved_found' => 'Ei yhtään käyttäjää odottamassa hyväksyntää',
		'not_logged_in' => 'Ole hyvä ja ^1kirjaudu^2 sisään ylläpitäjä päästääksesi tälle sivulle.',
		'opposite_main_menu' => 'Välilehdet ylhäällä',
		'options' => 'valinnat',
		'options_reset' => 'Valintojen nollaus',
		'options_saved' => 'Valinnan tallennettu',
		'page_already_used' => 'Tämä on jo käytössä toisella sivulla',
		'page_content_html' => 'Sisältö joka näytetään sivulla - HTML sallittu:',
		'page_default_slug' => 'sivu-^',
		'page_heading' => 'Otsikko, joka näytetään sivun yläreunassa.',
		'page_name' => 'Sivun nimi (käytetään myös välilehdessä tai linkissä):',
		'page_slug' => 'Sivuston etuliite (URL osanen):',
		'pages_explanation' => 'Paina \'Lisää sivu\' nappia lisääksesi muokattua sisältöä Q2A sivustolle, tai \'Lisää linkki\' lisätäksesi linkin toiselle sivulle.',
		'pages_title' => 'Sivut',
		'pause_mailing_button' => 'Keskeytä sähköpostiviestien lähetys',
		'per_ip_hour' => 'per IP/tunnissa',
		'per_user_hour' => 'per käyttäjä/tunnissa',
		'permissions_title' => 'Oikeudet',
		'permit_to_view' => 'Näkyy:',
		'php_version' => 'PHP versio:',
		'pixels' => 'pikselit',
		'plugin_module' => ' (lisäosan moduuli: ^)',
		'plugin_pages_explanation' => 'Sivut saatavilla lisäosien kautta:',
		'plugins_title' => 'Lisäosat',
		'points' => 'pisteet',
		'points_defaults_shown' => 'Oletusasetukset näkyvät alla, mutta ei vielä kytketty:',
		'points_required' => 'Vaaditut pisteet saadaksesi titteli:',
		'points_title' => 'Pisteet',
		'position' => 'Sijainti:',
		'posting_title' => 'Kirjoittaa',
		'profile_fields' => 'Lisäkentät käyttäjän sivulla tai rekisteröintilomakkeella:',
		'q2a_build_date' => 'Sivuston perustamispäivä:',
		'q2a_db_size' => 'Tietokannan koko:',
		'q2a_db_version' => 'Q2A tietokannan versio:',
		'q2a_latest_version' => 'Viimeisin versio:',
		'q2a_version' => 'Question2Answer versio:',
		'question_lists' => 'Kysymyslistat',
		'question_pages' => 'Kysymyssivut',
		'recalc_categories' => 'Laske uudelleen kategoriat',
		'recalc_categories_backpaths' => 'Uudelleenlaskee URL polut ^1 ja ^2 kategorioille..',
		'recalc_categories_complete' => 'Kaikki kategoriat uudelleenlaskettiin onnistuneesti.',
		'recalc_categories_note' => '- kirjoituksien kategorioiden ja kategorian laskentaa',
		'recalc_categories_recounting' => 'Uudelleenlaskee kysymykset ^1 ja ^2 kategorioissa...',
		'recalc_categories_updated' => 'Uudelleenlaskettu ^1 ja ^2 kirjoitukset...',
		'recalc_points' => 'Laske uudelleen käyttäjän pisteet',
		'recalc_points_complete' => 'Kaikki käyttäjän pisteet uudelleenlaskettiin onnistuneesti.',
		'recalc_points_note' => '- käyttäjien sijoituksen ja pisteiden näyttämiseksi',
		'recalc_points_recalced' => 'Uudelleenlaskettu ^1 ja ^2 käyttäjät...',
		'recalc_points_usercount' => 'Käyttäjämäärän arvio...',
		'recalc_posts_count' => 'Laskee kokonaismäärää kysymyksille, vastauksille ja kommentteille...',
		'recalc_stop' => 'Keskeytä uudelleenlaskenta',
		'recent_approve_title' => 'Viimeisimmät sisällöt odottamassa hyväksyntää',
		'recent_hidden_title' => 'Viimeisimmät piilotetut sisällöt',
		'recount_posts' => 'Laske uudelleen kirjoitukset',
		'recount_posts_as_recounted' => 'Uudelleenlaskettu vastaukset ja kuumuusarvo ^1 ja ^2 kirjoituksissa..',
		'recount_posts_complete' => 'Kaikkien kirjoituksien uudelleenlaskenta onnistui.',
		'recount_posts_note' => '- vastauksien, äänien, liputuksien ja kuumuusarvon arvo jokaisessa kirjoituksessa',
		'recount_posts_stop' => 'Keskeytä uudelleenlaskenta.',
		'recount_posts_votes_recounted' => 'Uudelleenlaskettu äänet ja liputukset ^1 ja ^2 kirjoituksessa...',
		'refill_events' => 'Uudelleentäytä tapahtumien striimi',
		'refill_events_complete' => 'Kaikkien tapahtumien striimit on uudelleentäytetty onnistuneesti.',
		'refill_events_note' => ' - jokaisen käyttäjän listan päivitykset',
		'refill_events_refilled' => 'Uudelleentäytetty ^1 ja ^2 kysymykset...',
		'registration_fields' => 'lisää rekisteröintikenttiä',
		'reindex_content' => 'Uudelleenindeksoi sisältö',
		'reindex_content_note' => ' - hakuihin ja samaan liittyvien kysymysten ehdotukset',
		'reindex_content_stop' => 'Keskeytä uudelleenindeksointi',
		'reindex_pages_reindexed' => 'Uudelleenindeksoitu ^1 ja ^2 sivut...',
		'reindex_posts_complete' => 'Kaikki kirjoitukset uudelleenindeksoitiin onnistuneesti.',
		'reindex_posts_reindexed' => 'Uudelleenindeksoitu ^1 ja ^2 kirjoitukset...',
		'reindex_posts_wordcounted' => 'Uudelleenlaskettu ^1 ja ^2 sanat...',
		'requires_php_version' => 'Estetty - vaatii PHP ^ tai uudemman',
		'requires_q2a_version' => 'Estetty - vaatii Question2Answer ^ tai uudemman',
		'reset_options_button' => 'Palauta oletusasetuksiin',
		'reset_options_confirm' => 'Oletko varma, että haluat resetoida kaikki valinnan oletusasetuksiin tällä sivulla?',
		'resume_mailing_button' => 'Jatka sähköpostien lähettämistä',
		'save_options_button' => 'Tallenna valinnat',
		'save_recalc_button' => 'Tallenna ja uudelleenlaske',
		'save_view_button' => 'Tallenna ja näytä',
		'send_test_button' => 'Lähetä testi minulle',
		'show_defaults_button' => 'Näytä oletusasetukset',
		'show_on_register_form' => 'Näytä kenttä käyttäjän rekisteröintilomakkeella',
		'slug_bad_chars' => 'Tämä liitesana ei saa sisältää näitä merkkejä: ^',
		'slug_reserved' => 'Tämä liitesana on varattu toisella sivulla',
		'spam_title' => 'Roskaposti',
		'start_mailing_button' => 'Aloita sähköpostiviestien lähetys',
		'stats_title' => 'Tilastot',
		'stop_recalc_warning' => 'Tietokannan puhdistuksen operaatio on kesken. Jos suljet sivun nyt niin operaatio keskeytyy.',
		'tag_pages' => 'Avainsanasivut',
		'tags' => 'Avainsanat',
		'tags_and_categories' => 'Avainsanat ja kategoriat',
		'tags_not_shown' => 'Osa kysymyksistä, joilla on avainsanoja, ei näytetä.',
		'test_sent_to_x' => 'Testausviesti lähetettiin osoitteeseen ^',
		'title_already_used' => 'Tämä arvo on jo käytetty toisessa otsikossa',
		'top_level_categories' => 'Pääkategoriat',
		'total_as' => 'Kaikki vastaukset:',
		'total_cs' => 'Kaikki kommentit:',
		'total_qs' => 'Kaikki kysymykset:',
		'unnamed_plugin' => 'Nimeämätön lisäosa',
		'upgrade_db' => 'Sinun Question2Answer tietokantasi vaatii ^1päivittämistä^2 tähän versioon.',
		'url_format_note' => 'Valinnat ^ lipulla toimivat sivuston asetuksilla. Hakukoneoptimointia (SEO) varten käytä ensimmäistä ^ valintaa.',
		'user_pages' => 'Käyttäjän sivut',
		'user_title' => 'Käyttäjän otsikko - HTML sallittu:',
		'user_titles' => 'Käyttäjän titteli perustuu pisteisiin:',
		'users_active' => 'Aktiiviset käyttäjät:',
		'users_must_have' => 'Käyttäjien pitää',
		'users_posted' => 'Käyttäjät jotka kirjoittivat:',
		'users_registered' => 'Rekisteröityneet käyttäjät:',
		'users_title' => 'Käyttäjät',
		'users_voted' => 'Käyttäjät, jotka ovat äänestäneet',
		'version_get_x' => 'saa ^',
		'version_latest' => 'viimeisin',
		'version_latest_unknown' => 'viimeisin tuntematon',
		'version_requires_php' => '^1 vaatii PHP ^2',
		'version_requires_q2a' => '^1 vaatii Q2A ^2',
		'viewing_title' => 'Katselee',
		'widget_all_pages' => 'Näytä vimpain samassa paikassa jokaisella sivulla',
		'widget_global_options' => ' - ^1valinnat^2',
		'widget_name' => 'Vimpaimen nimi:',
		'widget_no_positions' => 'Tämä vimpain on jo lisätty kaikille sopiville paikoille.',
		'widget_not_available' => 'Tämä vimpain ei ole saatavilla. Tilanne voi johtua siitä, että vimpainta tarjoava lisäosa ei ole enää asennettu.',
		'widget_pages_explanation' => 'Näytä vimpain tässä paikassa seuraavilla sivuilla:',
		'widgets_explanation' => 'Saatavilla olevat vimpaimet:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
